### ISSUE TITLE
[Bug]: Crashing after killing BMP 

### ISSUE THREAD

**Issue by zaylivinglive** [igorkis-scrts/A3-Antistasi-Plus#104]
### Describe the bug

Whenever destroying armor in Antistatsti, Shortly after cooking off the server will proceed to crash. I have attached the most recent crash log and dump of this. Looking at the crash log, it looks like its saying its a RAM issue, but there are over 24 gb of RAM free on the server it's hosted on, and we just got done playing liberation for a couple of weeks with more players and have not had this issue. Just to be on the safe side, I've opened it as a bug. 

### How to reproduce

Destroy a BMP with RPG 26

### Version

2.0

### Have you altered the code?

No

### Map

Virolahti

### What server?

Private dedicated server

### Mods

```html
"-mod=@A3 Thermal Improvement;@Advanced Rappelling;@CBA_A3;@CUP Terrains - Core;@DUI - Squad Radar;@Enhanced Movement;@Fawks' Enhanced NVGs;@Pylon Manager;@Remove stamina;@RHSAFRF;@RHSGREF;@RHSUSAF;@Vcom AI V3.4.0;@RHSSAF;@ACE Compat - RHS AFRF;@ACE Compat - RHS- GREF;@ACE Compat - RHS USAF;@Automated Ace No Medical;@Remove stamina - ACE 3;@ACE Compat - RHS- SAF;@AI avoids prone;@Advanced Towing;@Antistasi Plus 2.0;@Virolahti - Valtatie 7"
```

### Additional context

[arma3server_x64_2023-01-28_22-37-45.zip](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/10530747/arma3server_x64_2023-01-28_22-37-45.zip)

**Comment by igorkis-scrts** [comment]
Well, I have neither skills nor software to read memory dumps.
Some thoughts after reading the log:
1. The first I noticed that you have 
```
22:38:55 E:\NEW ARMA DIRECTORY\steamcmd\steamapps\common\Arma 3 Server\@RHSUSAF\addons\rhsusf_m1a1.pbo - RedHammerStudios.0.5.5.6698.r4419
22:38:55 E:\NEW ARMA DIRECTORY\steamcmd\steamapps\common\Arma 3 Server\@RHSUSAF\addons\rhsusf_m1a2.pbo - RedHammerStudios.0.5.6.6806.r4482
22:38:55 E:\NEW ARMA DIRECTORY\steamcmd\steamapps\common\Arma 3 Server\@RHSUSAF\addons\rhsusf_m252.pbo - RedHammerStudios.0.5.1.5659.r3805
```
Maybe it's perfectly normal (only RHS devs can say for sure), just looks strange that different pbos have different versions. If this happens with RHS, probably checking RHS files integrity would be good idea.
2. AI mods are not supported as they break mission's AI (units may run away from outpost or leave the task area, refuse to comply with player commands etc). Also, VCOM AI regularly throws this script error into log:
```
Bad conversion: scalar
Error in expression <QSTHELP",false];};
private _trgtPos = getpos _killer;
if (isPlayer _unit) ex>
  Error position: <getpos _killer;
if (isPlayer _unit) ex>
  Error getpos: Type String, expected Object,Location
File vcomai\Vcom\Functions\VCM_Functions\fn_ClstWarn.sqf..., line 30
```
So, it is good idea to remove VCOM AI mod in this case.
3. Crash code is pretty generic and per BI troubleshooting usually means general system problems:
https://community.bistudio.com/wiki/Arma_3:_Unusual_Process_Exit#0xC0000005_-_ACCESS_VIOLATION


Since server were able to work from `22:37:45 28.01.2023` to `2023-01-29 08:09:39:541` without crashing and considering that that's it's very hard, almost impossible to cause CTD via SQF gameplay code and, of course, crash exception code, it reinforces my thoughts that's it's indeed an actual hardware/OS issue. I'm playing with RHS and 3CBF myself on dedicated server and this does not happens to me, so seems to be some sort of hardware or game issue.
I would suggest to check your general server health - check OS health, run memtest and some HDD/SSD troubleshooting software to see if there are any bad blocks/unreadable sectors, check overall game and mods integrity (for example, sometimes FASTER, very popular DS management tool, may download mod with some corrupted .pbos, happened to me twice). 
Also, it would be good idea to play with only necessary mods (in your case it's Virolahti and RHS) and see if issue persists. If not, then you could add mods one by one to find faulty one.

**Comment by igorkis-scrts** [comment]
Closing as no input from ticket starter.
