### ISSUE TITLE
HR  given

### ISSUE THREAD

**Issue by alex200093** [igorkis-scrts/A3-Antistasi-Plus#11]
I am recruiting a prisoner and I am not given HR for this

**Comment by igorkis-scrts** [comment]
You mean POWs on Rescue tasks or enemy surrended soldiers? In the first case, HR income should be applied on mission complete (when you deliver them to the HQ).

**Comment by alex200093** [comment]
surrendered soldiers

**Comment by igorkis-scrts** [comment]
HR is given, there was no proper notification.
![image1](https://user-images.githubusercontent.com/6746043/101756359-fd361080-3ae6-11eb-8237-f382afe3ac31.png)
![image2](https://user-images.githubusercontent.com/6746043/101756444-1212a400-3ae7-11eb-8583-b279678a3c5e.png)

Anyway, thanks for report, notification will be fixed in **1.4.1**.

**Comment by alex200093** [comment]
hmm it doesn't give me ...
https://youtu.be/D_CyBT56i7Q

**Comment by igorkis-scrts** [comment]
It has delayed income (about 2 minutes).

**Comment by alex200093** [comment]
I recorded a video 30 min ago I still have 1 HR I have already recruited > 10 people

**Comment by igorkis-scrts** [comment]
![img32321](https://user-images.githubusercontent.com/6746043/101763757-48a0ec80-3af0-11eb-8f1a-8a0d38d68a2b.png)
On your video, they're not agreeing to join thus why you have no HR income.

They should agree to be recruited.
![img212131](https://user-images.githubusercontent.com/6746043/101763805-57879f00-3af0-11eb-83fd-6ed8f0077812.png)

**Comment by alex200093** [comment]
Well, then it's more of a balance problem because I've already tried to recruit> 20 people and not one of them agreed
