### ISSUE TITLE
[Bug]: Friendly Squad A.I. can cause an out of body experience if downed

### ISSUE THREAD

**Issue by FuckingStealingNames** [igorkis-scrts/A3-Antistasi-Plus#118]
### Describe the bug

If you're in a single person squad (you and another A.I.),and you're downed, and this A.I. dies via pressing the respawn button whilst controlling, you will get in a state where you're not in your own body anymore.

An alternative and probably more likely state will happen where you can also have this happen if you take over an A.I., and have your main body instantly killed (explosion most likely).

### How to reproduce

1. Make sure you're alone, no squad members of any kind
2. Get a squad member, like a medic
3. Be downed on your main body
4. Take over the A.I.
5. Die instantly by a damage source (like an explosive RPG)
6. Experience an out of body bug

OR
1 thru 4
5. Press the respawn button while in the A.I.
6. Experience an out of body experience that softlocks you entirely if you die.

### Version

2.1.2

### Have you altered the code?

No

### Map

N/A

### What server?

LAN Hosted

### Mods

```html
Only Antistasi Plus
```

**Comment by igorkis-scrts** [comment]
Non-fixable because of game/engine limitations - AI control works through `selectPlayer` command and it basically moves you from your slot-unit from game lobby with tied game logic to another runtime created one (AI unit which was spawned by various game systems). To prevent situations like this to happen, there are two event handlers to immideately return your to your body in case of any damage either you or controllable unit takes (`Hit` EHs are executed earlier than `Killed`), this is why it doesn't happen in ordinary gameplay.
So the only solution is to not press Respawn button.
