### ISSUE TITLE
[Change Request]: Allow adding RHS' single-use launcher ammunition through the arsenal

### ISSUE THREAD

**Issue by Alexandre425** [igorkis-scrts/A3-Antistasi-Plus#135]
### Is the requested change related to a problem?

AI cannot use RHS' single use launchers unless they have at least one of the respective rockets in their inventory (this isn't an issue for players as reloading with the launcher creates a rocket in the ammo slot)

### Describe the solution you'd like.

These rockets appear in the arsenal, but it's not possible to actually add them. If it's possible, fixing this would allow giving friendly AI single use launchers.

**Comment by igorkis-scrts** [comment]
They can be added to backpacks only. Not an Antistasi Plus issue as I can't change how RHS coded their launchers.

**Comment by Alexandre425** [comment]
I can't seem to add them anywhere, backpacks included. I understand it has to do with how RHS does things differently, but isn't it possible to change the arsenal such that you could add those?

**Comment by igorkis-scrts** [comment]
Investigated it a bit - well, single shot RPGs ammo add actually works, but amount counter is broken due to zero weight/mass of such items (it changes counter only if old and new weight differs):
![20230311200308_1](https://user-images.githubusercontent.com/6746043/224500386-2b665d2b-85b4-45e7-99c1-c61cae636b06.jpg)

Removing this code (which seems to be unnecessary on first glance) completely breaks adding anything to arsenal:
![20230311195814_1](https://user-images.githubusercontent.com/6746043/224498624-df3abf7e-956a-44c5-ad2b-4663470b4646.jpg)

So, since the bug is pretty minor and visual only and considering that fact that the arsenal codebase is easily breakable mess (it hasn't changed much since original Antistasi and is a hot mess of a code) I'm afraid it won't be fixed unless someone will do a full rewrite of arsenal.

**Comment by Alexandre425** [comment]
Oh, I understand, so it adds them but you cannot see it. That should be good enough for now, thank you.
