### ISSUE TITLE
Taviana version of the mission is inoperable on dedicated server

### ISSUE THREAD

**Issue by lordkabal26** [igorkis-scrts/A3-Antistasi-Plus#18]
**Describe the bug**
Taviana loads Utes when run on a dedicated server no matter what mod set is used or even vanilla

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant): Put the mission file on a dedicated server and try loading it

**Expected behaviour**
Sever should be loading Taviana instead of Utes

**Screenshots**
Server Role Assignment: https://puu.sh/H8C92/ff7aa00d4c.png

Local Hosted LAN for comparison: https://puu.sh/H8CbM/10c9235705.png

Server Map Screen: https://puu.sh/H8Cwq/86f780218c.png

Local Hosted LAN map Screen for comparison: https://puu.sh/H8Cyw/39ebf45815.png

**Environment (please complete the following information):**
Version:  Latest Version
Map (specify if Altis Blufor): Taviana

* [ ] LAN Hosted
* [X ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset: Doesn't matter affected even vanilla, RPTs will have CUP set though.

    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 
Started when I tried to load up a dedicated server at around 7pm CST

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

Included the LAN RPT to show that it loaded properly compared to dedicated

[RPTs.zip](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/5839965/RPTs.zip)

**Comment by lordkabal26** [comment]
Tested on a whim with the previous 1.4.1 version and it loaded properly, so there's something broken with the 1.4.2 version with dedicated servers

**Comment by igorkis-scrts** [comment]
I see in the .rpt logs that you're using modified/edited mission - **AntistasiPlusTavi** is definetely not **Antistasi Plus - Taviana**.
Usually i'm not providing any support on any custom forks and edits since i don't know what's exactly was changed, but it looks like i know what happened in your case.

For some reason you have renamed mission postfix from `taviana` to `Tavi` (why though..?). Arma uses mission file postfix to determine mission `worldname` - Taviana map mod uses `taviana` worldname so to correctly load mission on Taviana mission file needs to use. So, after you renamed it to`Tavi`, map detection has been broken, so it loads default map (for some reason this default map is Utes - looks like Arma 2 legacy code in Arma 3) instead:

```
22:20:52 Starting mission:
22:20:52  Mission file: AntistasiPlusTavi (__cur_mp)
22:20:52  Mission world: Tavi
...
22:21:03 [CBA] (xeh) INFO: [14216,336.251,0] PostInit started. MISSIONINIT: missionName=AntistasiPlusTavi, missionVersion=53, worldName=Tavi, isMultiplayer=true, isServer=true, isDedicated=true, CBA_isHeadlessClient=false, hasInterface=false, didJIP=false
```

Also, worldname postfix rename breaks Antistasi too:
```
22:22:38 Warning Message: Script Navigation\navGridTavi.sqf not found
22:22:38 "397.891: [Antistasi] | INFO | fn_loadNavGrid | Finished loading nav grid"
22:22:38 Error in expression <rker;
} forEach _mainMarkers;
} forEach navGrid;

roadDataDone = true;

[2, "Fin>
22:22:38   Error position: <navGrid;

roadDataDone = true;

[2, "Fin>
22:22:38   Error Undefined variable in expression: navgrid
```

`navGridTavi.sqf` file does not exist, but navGridtaviana.sqf is there, so mission predefined navgrid detection brokes too, renders mission unplayable.

Conclusion: this have nothing to do with **1.4.2** update or Antistasi Plus itself. Hope, that investigation above helps to heal your custom edit.
