### ISSUE TITLE
Server autorestart

### ISSUE THREAD

**Issue by wp1g19** [igorkis-scrts/A3-Antistasi-Plus#23]
**Is your feature request related to a problem? Please describe.**
I'm running a persistent server and as usual, over 6 hours the server FPS alls significantly. A server restart fixes the issue.

**Describe the solution you'd like**
The integration of a server restart command in the antistasi mission along the lines of KP liberation, an example provided from KP liberation.
[server_restart.sqf.txt](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/5939467/server_restart.sqf.txt)
[KP init.sqf.txt](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/5939468/KP.init.sqf.txt)

**Describe alternatives you've considered**
Alternatives include old Bat files for server restart but these aren't compatible with server managers such as FASTER.

**Additional context**
Not really additional context, but we're really enjoying the plus version and I'm looking forward to 2.0, keep up the great work.

**Comment by SpadesNeil** [comment]
My server usually manages to last about 24 hours before needing a reset, usually because things start getting buggy and less due to FPS loss.

FPS loss sounds like an issue with cleanup. I would suggest running the cleanup script more often as commander.

That all being said, the convenience of a restart script would be nice. I have no idea if it's possible for a steam download to include such content. I would configure it according to preference.

**Comment by igorkis-scrts** [comment]
I think this kind of behaviour should be done on dedicated server level, not on the mission level.
The main source of FPS problems are commanders who's not using Clean Garbage button.
