### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by lelun** [igorkis-scrts/A3-Antistasi-Plus#61]
### Related problem

unable to start the mission with both CUP and RHS enabled.

### Proposed feature

Reqesting to either have 2 variants 1 for cup and 1 for RHS. where you can have both mods on but only one will be used to spawn units.

### Alternative solutions

having a system that premits for the use of both mods at the same time on the server with out been forced kicked back to the menu.
maybe as a option in the option menu what mod faction we want to fight where we cab select a yes or no option to the mods
example
RHS:yes
CUP:no
CB3:no

### Additional context

on the server that i play on we have a set mod set where we would like to be able to play this mission with out re jiging the server for this spesific mission. this is why i am requesting a feature where we can boot the mission with both RHS and CUP on the server, but only selecting one mods factions to fight at the time. with out the need for changing the server mod sett.

**Comment by igorkis-scrts** [comment]
Won’t be done due to:
1. RHS and CUP working simultaneously has unresolved conflicts in Antistasi Plus’s code which leads to runtime errors.
2. RHS and CUP are not compatible without compatibility mods, they work questionable at best.
3. Mod autodetection code should be changed too much for this very specific request.

**Comment by lelun** [comment]
HI thanks for explaining why it will not be done. 
Have a good day :)
