### ISSUE TITLE
Arms Dealer - Buy to unlock gun in arsenal

### ISSUE THREAD

**Issue by Johnston524** [igorkis-scrts/A3-Antistasi-Plus#9]
Would make life easier if buy function at arms dealer unlocks the gun in the arsenal rather than making player carry 15 guns back to HQ.

**Comment by asumadelta** [comment]
i heard Arms Dealer have function that you can move Arms Dealer to your HQ for 5000$ that mean you can buy weapons to your box or vehicle than add to arsenal

**Comment by Johnston524** [comment]
Aye granted, but you still have the tedium of buying 15 guns, adding to box and repeating. Would be much easier to just have a cost of 12k for x weapon as a one time purchase.

**Comment by asumadelta** [comment]
sorry if i misunderstand ,  blue mark you type how many you want to buy at one time  and red mark if you bring vehicle close enough you can select   , that mean what you need to do next is add to arsenal

![image](https://user-images.githubusercontent.com/23005914/101508680-8b58ac80-39aa-11eb-9ef8-c3477a988720.png)

**Comment by Johnston524** [comment]
Oh I see, okay that makes sense now.

**Comment by igorkis-scrts** [comment]
Well, rethinking about it - it is definetely possible, someday i will add that functionality.

**Comment by Randomisation** [comment]
> Move Arms Dealer to rebel HQ laptop action

Has this been implemented? I do not get this option (I am using the latest version).

**Comment by igorkis-scrts** [comment]
@Randomisation
It was removed in **1.4.2** due to inability to make it properly on all server configurations (for some unidentified reason store objects were not transferred but duplicated). It was replaced with arms dealer terminal (opt-in).

**Comment by SpadesNeil** [comment]
> Would make life easier if buy function at arms dealer unlocks the gun in the arsenal rather than making player carry 15 guns back to HQ.

I think a good balance reason for why this _**shouldn't**_ be implemented is because players shouldn't be allowed to unlock the guns in the arsenal without some work.

In fact, I argue it's intentional that players can't do this. So, 15 guns isn't enough to unlock the weapon in the arsenal. You therefore _cannot_ unlock a gun in one day with one trip to the arms dealer. To unlock guns that you really want you have to make multiple trips to the arms dealer after they restock.

It shouldn't be possible for people to unlock, say, thermal weapon sights with the click of a button no matter how much money they have. In that case, there's only 5 at a time. At minimum you have to wait **almost five real-life days** assuming you have the money (which you usually don't) to unlock this. Also assuming I have the cooldown timer right in my head. Might be tied to server reset, idk.

**Comment by igorkis-scrts** [comment]
To be honest, i tend to agree with @SpadesNeil. Buy to unlock feature will break traditional Antistasi gameplay loop with supply boxes - why even bother with them when you can basically buy almost everything? 
Arms Dealer store is meant to complement default loot gaining mechanics, not fully replace them.
